# Generated by Django 4.0.1 on 2023-08-19 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_account_credentials_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=210, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Major Requirement', 'Major Requirement'), ('Minor Requirement', 'Minor Requirement'), ('Capstone Project', 'Capstone Project')], default='Major Requirement', max_length=50)),
                ('keyword', models.CharField(blank=True, max_length=30, null=True)),
                ('keyword_description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(50, 'the field must be at least 50 characters')])),
                ('key_aspects', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(50, 'the field must be at least 50 characters')])),
            ],
        ),
    ]
